### ISSUE TITLE
library please

### ISSUE THREAD

**Issue by hoodie** [Feliix42/ifsr_anybar#1]
Hey, I'd kinda like to use this elsewhere.
Could you expose this as a library? Maybe with a nice API, and all the docs :grinning: 

:+1:

**Comment by Feliix42** [comment]
Sounds like a lot of fun! I will definitely do this! 😊 
I will let you know how it's going!

**Comment by Feliix42** [comment]
Wait a minute, are you talking about the "is the office open" functionality or the AnyBar connection? 😄

**Comment by hoodie** [comment]
I was talking about the former, but thinking about it .. this may be two libs :grinning:

**Comment by Feliix42** [comment]
I'm actually thinking about writing a lib for the AnyBar connection anyway. So why not both? :D

**Comment by Feliix42** [comment]
[There](https://github.com/feliix42/anybar-rs) and [there](https://github.com/feliix42/buerostatus-rs) you go! :)
